# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergei/Projects/PairAnalysisPhenix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergei/Projects/PairAnalysisPhenix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/PairAnalysisPhenix/CMakeFiles /home/sergei/Projects/PairAnalysisPhenix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/PairAnalysisPhenix/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/PairAnalysisPhenix/CMakeFiles /home/sergei/Projects/PairAnalysisPhenix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/PairAnalysisPhenix/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EffTreeReader

# Build rule for target.
EffTreeReader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EffTreeReader
.PHONY : EffTreeReader

# fast build rule for target.
EffTreeReader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EffTreeReader.dir/build.make CMakeFiles/EffTreeReader.dir/build
.PHONY : EffTreeReader/fast

#=============================================================================
# Target rules for targets named ErrorHandler

# Build rule for target.
ErrorHandler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ErrorHandler
.PHONY : ErrorHandler

# fast build rule for target.
ErrorHandler/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/ErrorHandler.dir/build.make CppTools/CMakeFiles/ErrorHandler.dir/build
.PHONY : ErrorHandler/fast

#=============================================================================
# Target rules for targets named StrTools

# Build rule for target.
StrTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StrTools
.PHONY : StrTools

# fast build rule for target.
StrTools/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/StrTools.dir/build.make CppTools/CMakeFiles/StrTools.dir/build
.PHONY : StrTools/fast

#=============================================================================
# Target rules for targets named Time

# Build rule for target.
Time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Time
.PHONY : Time

# fast build rule for target.
Time/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/Time.dir/build.make CppTools/CMakeFiles/Time.dir/build
.PHONY : Time/fast

#=============================================================================
# Target rules for targets named IOTools

# Build rule for target.
IOTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IOTools
.PHONY : IOTools

# fast build rule for target.
IOTools/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/IOTools.dir/build.make CppTools/CMakeFiles/IOTools.dir/build
.PHONY : IOTools/fast

#=============================================================================
# Target rules for targets named Box

# Build rule for target.
Box: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Box
.PHONY : Box

# fast build rule for target.
Box/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/Box.dir/build.make CppTools/CMakeFiles/Box.dir/build
.PHONY : Box/fast

#=============================================================================
# Target rules for targets named Table

# Build rule for target.
Table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Table
.PHONY : Table

# fast build rule for target.
Table/fast:
	$(MAKE) $(MAKESILENT) -f CppTools/CMakeFiles/Table.dir/build.make CppTools/CMakeFiles/Table.dir/build
.PHONY : Table/fast

#=============================================================================
# Target rules for targets named TCanvasTools

# Build rule for target.
TCanvasTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TCanvasTools
.PHONY : TCanvasTools

# fast build rule for target.
TCanvasTools/fast:
	$(MAKE) $(MAKESILENT) -f ROOTTools/CMakeFiles/TCanvasTools.dir/build.make ROOTTools/CMakeFiles/TCanvasTools.dir/build
.PHONY : TCanvasTools/fast

#=============================================================================
# Target rules for targets named TF1Tools

# Build rule for target.
TF1Tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TF1Tools
.PHONY : TF1Tools

# fast build rule for target.
TF1Tools/fast:
	$(MAKE) $(MAKESILENT) -f ROOTTools/CMakeFiles/TF1Tools.dir/build.make ROOTTools/CMakeFiles/TF1Tools.dir/build
.PHONY : TF1Tools/fast

#=============================================================================
# Target rules for targets named ThrObj

# Build rule for target.
ThrObj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThrObj
.PHONY : ThrObj

# fast build rule for target.
ThrObj/fast:
	$(MAKE) $(MAKESILENT) -f ROOTTools/CMakeFiles/ThrObj.dir/build.make ROOTTools/CMakeFiles/ThrObj.dir/build
.PHONY : ThrObj/fast

#=============================================================================
# Target rules for targets named GUIDistrCutter2D

# Build rule for target.
GUIDistrCutter2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUIDistrCutter2D
.PHONY : GUIDistrCutter2D

# fast build rule for target.
GUIDistrCutter2D/fast:
	$(MAKE) $(MAKESILENT) -f ROOTTools/CMakeFiles/GUIDistrCutter2D.dir/build.make ROOTTools/CMakeFiles/GUIDistrCutter2D.dir/build
.PHONY : GUIDistrCutter2D/fast

#=============================================================================
# Target rules for targets named PBar

# Build rule for target.
PBar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PBar
.PHONY : PBar

# fast build rule for target.
PBar/fast:
	$(MAKE) $(MAKESILENT) -f ProgressBar/CMakeFiles/PBar.dir/build.make ProgressBar/CMakeFiles/PBar.dir/build
.PHONY : PBar/fast

src/EffTreeReader.o: src/EffTreeReader.cpp.o
.PHONY : src/EffTreeReader.o

# target to build an object file
src/EffTreeReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EffTreeReader.dir/build.make CMakeFiles/EffTreeReader.dir/src/EffTreeReader.cpp.o
.PHONY : src/EffTreeReader.cpp.o

src/EffTreeReader.i: src/EffTreeReader.cpp.i
.PHONY : src/EffTreeReader.i

# target to preprocess a source file
src/EffTreeReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EffTreeReader.dir/build.make CMakeFiles/EffTreeReader.dir/src/EffTreeReader.cpp.i
.PHONY : src/EffTreeReader.cpp.i

src/EffTreeReader.s: src/EffTreeReader.cpp.s
.PHONY : src/EffTreeReader.s

# target to generate assembly for a file
src/EffTreeReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EffTreeReader.dir/build.make CMakeFiles/EffTreeReader.dir/src/EffTreeReader.cpp.s
.PHONY : src/EffTreeReader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Box"
	@echo "... EffTreeReader"
	@echo "... ErrorHandler"
	@echo "... GUIDistrCutter2D"
	@echo "... IOTools"
	@echo "... PBar"
	@echo "... StrTools"
	@echo "... TCanvasTools"
	@echo "... TF1Tools"
	@echo "... Table"
	@echo "... ThrObj"
	@echo "... Time"
	@echo "... src/EffTreeReader.o"
	@echo "... src/EffTreeReader.i"
	@echo "... src/EffTreeReader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

